#!/bin/bash

icon="$HOME/.config/i3/images/lockicon.png"
tmpbg='/tmp/screen.png'

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"

# suspend message display
pkill -u "$USER" -USR1 dunst

# kill compton
pkill -u "$USER" compton

# lock the screen
i3lock -i "$tmpbg" -n -e

# resume message display
pkill -u "$USER" -USR2 dunst

# restart compton
compton
